# Generated by Django 5.1.7 on 2025-03-31 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
        ('genre', '0001_initial'),
        ('publication', '0001_initial'),
        ('volume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('publication_year', models.PositiveBigIntegerField(blank=True, null=True)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('description', models.TextField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdf-files/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
                ('published_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_author', to='author.author')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_genre', to='genre.genre')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_publication', to='publication.publication')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_volume', to='volume.volume')),
            ],
        ),
    ]
