# Generated by Django 5.1.7 on 2025-04-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_book_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('paperback', 'Paperback'), ('hardcover', 'Hardcover')], default='hardcover', max_length=10),
        ),
    ]
