# Generated by Django 5.1.7 on 2025-04-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_book_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=1, editable=False, max_length=255),
            preserve_default=False,
        ),
    ]
