# Generated by Django 5.1.7 on 2025-04-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slog',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('hardcover', 'Hardcover'), ('paperback', 'Paperback')], default='hardcover', max_length=10),
        ),
    ]
