# Generated by Django 5.1.7 on 2025-04-03 11:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_book_slog_alter_book_book_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('paperback', 'Paperback'), ('hardcover', 'Hardcover')], default='hardcover', max_length=10),
        ),
    ]
